### PR TITLE
[list-comprenhension] Enmanuel Adonis Lafuente Ramos

### PR DESCRIPTION
**Pull request by Adonis232**

### CODE REVIEW

**Comment by ta-data-mad** [comment]
Please add your name to the pull request!

**Comment by Adonis232** [comment]
Fixed!!! , sorry I forgot

**Comment by ta-data-mad** [comment]
Hello Enmanuel!

Challenges completed: 5/7

Bonus completed: 0/9

Questions/Comments: you were doing it very well! So sad that you couldn't do the ones with the conditiond, you should just have to add < or > depending on the case to the element of the list you were evaluating, I think you put it to the list and that's why it gave you an error

Future tip: Whenever you can, try to use list comprehensions, in order to have a cleaner and more readable code.
Here is an interesting post with list comprehension cases.

Status: #needs_improvement

**Comment by ta-data-mad** [comment]
Also please check your branches and the lfiles you upload because it appears files from other labs such as bash master, string operations...

**Pull request closed without merging**
